### ISSUE TITLE
Add docstrings

### ISSUE THREAD

**Issue by alxndrkalinin** [cytomining/copairs#71]
Most package code is missing docstrings.

Since we switched to [ruff](https://docs.astral.sh/ruff/faq/#does-ruff-support-numpy-or-google-style-docstrings) for linting and formatting, we can enforce docstrings by adding following to pyproject.toml and to github actions.

```toml
[tool.ruff.lint]
select = ["D"]

[tool.ruff.lint.pydocstyle]
convention = "numpy"
```
